/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.3.3
 * Product:       sps30
 * Model-Version: 1.0.1
 */
/*
 * Copyright (c) 2025, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef SPS30_UART_H
#define SPS30_UART_H

#ifdef __cplusplus
extern "C" {
#endif

#include "sensirion_config.h"
#define SPS30_SHDLC_ADDR 0x00

typedef enum {
    SPS30_START_MEASUREMENT_CMD_ID = 0x0,
    SPS30_STOP_MEASUREMENT_CMD_ID = 0x1,
    SPS30_READ_MEASUREMENT_VALUES_UINT16_CMD_ID = 0x3,
    SPS30_READ_MEASUREMENT_VALUES_FLOAT_CMD_ID = 0x3,
    SPS30_SLEEP_CMD_ID = 0x10,
    SPS30_WAKE_UP_COMMUNICATION_CMD_ID = 0xff,
    SPS30_WAKE_UP_CMD_ID = 0x11,
    SPS30_START_FAN_CLEANING_CMD_ID = 0x56,
    SPS30_READ_AUTO_CLEANING_INTERVAL_CMD_ID = 0x80,
    SPS30_WRITE_AUTO_CLEANING_INTERVAL_CMD_ID = 0x80,
    SPS30_READ_PRODUCT_TYPE_CMD_ID = 0xd0,
    SPS30_READ_SERIAL_NUMBER_CMD_ID = 0xd0,
    SPS30_READ_VERSION_CMD_ID = 0xd1,
    SPS30_READ_DEVICE_STATUS_REGISTER_CMD_ID = 0xd2,
    SPS30_DEVICE_RESET_CMD_ID = 0xd3,
} SPS30_CMD_ID;

typedef enum {
    SPS30_OUTPUT_FORMAT_OUTPUT_FORMAT_FLOAT = 259,
    SPS30_OUTPUT_FORMAT_OUTPUT_FORMAT_UINT16 = 261,
} sps30_output_format;

int16_t sps30_wake_up_sequence();
int16_t sps30_start_measurement(sps30_output_format measurement_output_format);
int16_t sps30_stop_measurement();
int16_t sps30_read_measurement_values_uint16(
    uint16_t* mc_1p0, uint16_t* mc_2p5, uint16_t* mc_4p0, uint16_t* mc_10p0,
    uint16_t* nc_0p5, uint16_t* nc_1p0, uint16_t* nc_2p5, uint16_t* nc_4p0,
    uint16_t* nc_10p0, uint16_t* typical_particle_size);
int16_t sps30_read_measurement_values_float(float* mc_1p0, float* mc_2p5,
                                            float* mc_4p0, float* mc_10p0,
                                            float* nc_0p5, float* nc_1p0,
                                            float* nc_2p5, float* nc_4p0,
                                            float* nc_10p0,
                                            float* typical_particle_size);
int16_t sps30_sleep();
int16_t sps30_wake_up_communication();
int16_t sps30_wake_up();
int16_t sps30_start_fan_cleaning();
int16_t sps30_read_auto_cleaning_interval(uint32_t* auto_cleaning_interval);
int16_t sps30_write_auto_cleaning_interval(uint32_t auto_cleaning_interval);
int16_t sps30_read_product_type(int8_t* product_type, uint16_t product_type_size);
int16_t sps30_read_serial_number(int8_t* serial_number, uint16_t serial_number_size);
int16_t sps30_read_version(uint8_t* firmware_major_version,
                           uint8_t* firmware_minor_version, uint8_t* reserved1,
                           uint8_t* hardware_revision, uint8_t* reserved2,
                           uint8_t* shdlc_major_version,
                           uint8_t* shdlc_minor_version);
int16_t sps30_read_device_status_register(bool clear_status_register,
                                          uint32_t* device_status_register,
                                          uint8_t* reserved);
int16_t sps30_device_reset();

#ifdef __cplusplus
}
#endif
#endif  // SPS30_UART_H
